### ISSUE TITLE
AJAX Error when locking topics

### ISSUE THREAD

**Issue by francinum** [m-ober/phpbb-discord-notifications#16]
Since the lock thread event doesn't include `post_id`, `post_subject`, `poster_id`, or `username`, it results in 4 PHP errors, which end up logging to HTML, and polluting the JSON response, causing bad moderator feedback.

I patched this on my forum by null-coalescing these values, though I have not tested whether this causes issues with the respective event hook, as we don't use the topic lock hooks for our community.
```diff
                $lock_data = array();
                $lock_data['forum_id'] = $event['data'][$id]['forum_id'];
                $lock_data['forum_name'] = $event['data'][$id]['forum_name'];
+               $lock_data['post_id'] = $event['data'][$id]['post_id'] ?? null;
+               $lock_data['post_subject'] = $event['data'][$id]['post_subject'] ?? null;
                $lock_data['topic_id'] = $event['data'][$id]['topic_id'];
                $lock_data['topic_title'] = $event['data'][$id]['topic_title'];
                // Two sets of user data captured: one for the post (if applicable) and one for the user that started the topic
+               $lock_data['post_user_id'] = $event['data'][$id]['poster_id'] ?? null;
+               $lock_data['post_user_name'] = $event['data'][$id]['username'] ?? null;
                $lock_data['topic_user_id'] = $event['data'][$id]['topic_poster'];
                $lock_data['topic_user_name'] = $event['data'][$id]['topic_first_poster_name'];
```

**Comment by m-ober** [comment]
Finally found some time to look into this, it has been reported multiple times, always im combination with the "quickmod" extension. Your solution is indeed correct, as for some events those fields are not set and also not needed.

I published a new version with this fix and some other small improvements:

https://github.com/m-ober/phpbb-discord-notifications/releases/tag/3.0.7-release

Fixed in 98655f52d35bc5df3696f5e5294675a99940dcc2
